# Example Home Assistant configuration for the S7 integration

s7plc:
  host: 192.168.0.10
  rack: 0
  slot: 1
  scan_interval: 0.5

sensor:
  - platform: s7plc
    name: Temperatura
    address: "DB60.DBD0"    # real/float/int

binary_sensor:
  - platform: s7plc
    name: "Test Binary Sensor"
    address: "DB58.DBX0.4" # bit

switch:
  - platform: s7plc
    name: Uscita Sirena
    address: "DB20.DBX0.3"

light:
  - platform: s7plc
    name: Uscita Sirena
    address: "DB20.DBX0.5"
