# Example Home Assistant configuration for the S7 integration

light:
  - platform: s7plc
    name: "Test Light"
    address: "DB58.DBX0.6"
    plc:
       host: 192.168.100.89   # indirizzo IP del PLC
       rack: 0
       slot: 1
       port: 102  
       
switch:
  - platform: s7plc
    name: "Test Switch"
    address: "DB58.DBX0.7"
    plc:
       host: 192.168.100.89   # indirizzo IP del PLC
       rack: 0
       slot: 1
       port: 102  

sensor:
  - platform: s7plc
    name: "Test Sensor"
    address: "DB58.I2"
    unit_of_measurement: "°C"
    plc:
       host: 192.168.100.89   # indirizzo IP del PLC
       rack: 0
       slot: 1
       port: 102  
