# Example Home Assistant configuration for the S7 integration

light:
  - platform: s7
    name: "Test Light"
    address: "DB1.DBX0.0"

switch:
  - platform: s7
    name: "Test Switch"
    address: "DB1.DBX0.1"

sensor:
  - platform: s7
    name: "Test Sensor"
    address: "DB1.DBR2"
    unit_of_measurement: "°C"
    plc:
       host: 192.168.1.100   # indirizzo IP del PLC
       rack: 0
       slot: 1
       port: 102  