name: "Bug report"
description: "Report a problem with ha-s7plc"
title: "[BUG] <short title>"
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill out the details below."

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-checks
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have restarted Home Assistant and the issue persists
        - label: I have enabled debug logging (if applicable)

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant version
      placeholder: "e.g., 2025.6.3"
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: ha-s7plc integration version
      placeholder: "e.g., 1.2.0 (HACS) or commit SHA"
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: Installation method
      options: [HACS, Manual, Other/Unknown]
    validations:
      required: true

  - type: dropdown
    id: plc_model
    attributes:
      label: PLC model
      options: [S7-1200, S7-1500, Logo!, Other/Unknown]
    validations:
      required: true

  - type: input
    id: plc_fw
    attributes:
      label: PLC firmware (optional)
      placeholder: "e.g., V4.5.2"

  - type: dropdown
    id: optimized_db
    attributes:
      label: Optimized data block
      options: [Yes, No, Unknown]
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: "What actually happens? Include any error messages."
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Relevant configuration
      placeholder: |
        Paste relevant YAML or settings (do not include secrets).

  - type: textarea
    id: logs
    attributes:
      label: Debug logs
      placeholder: |
        Paste relevant log lines.

  - type: textarea
    id: extra
    attributes:
      label: Additional details
      placeholder: "Environment, container, OS, etc."
