name: "Bug report"
description: "Report a problem with ha-s7plc"
title: "[BUG] <short title>"
labels: ["bug"]
body:
  - type: input
    id: ha_version
    attributes:
      label: Home Assistant version
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
